function refreshDashboard(){buildBreakdown_();buildMaster_();buildCharts_();}
function periodBounds_(){return {start:'IF($B$5="Custom",$B$3,IF($B$5="All Time",DATE(1900,1,1),IF($B$5="Last 30 Days",TODAY()-29,EDATE(TODAY(),-VALUE(REGEXEXTRACT($B$5,"\\d+")))))',end:'IF($B$5="Custom",$B$4,TODAY())'};}
function buildBreakdown_(){
 const s=mbSheet_('EV Breakdown'),period=MB.PERIODS.includes(s.getRange('B5').getValue())?s.getRange('B5').getValue():'All Time',from=s.getRange('B3').getValue(),to=s.getRange('B4').getValue();mbEnsureSize_(s,100,23);s.getRange(1,1,s.getMaxRows(),23).clearContent();s.getRange('A1:W1').merge().setValue('EV BREAKDOWN — performance for the selected reporting period');
 s.getRange('A3:B7').setValues([['Custom From',from],['Custom To',to],['Reporting Period',period],['Window From',''],['Window To','']]);const b=periodBounds_();s.getRange('B6').setFormula('='+b.start);s.getRange('B7').setFormula('='+b.end);
 breakdownTable_(s,9,1,'PROMOS',['Promo Type','Turnover','Estimated EV','Actual PnL','EV %','POT %','Percentage of Promo Turnover'],MB.PROMOS.map(x=>x[0]),'Promos','C','E','H',['I','J'],b,'#17652a');
 breakdownTable_(s,9,9,'NONPROMOS',['Non-Promo Type','Turnover','Expected EV','EV %','Actual PnL','POT %','Percentage of Non-Promo Turnover'],MB.NON_TYPES,'NonPromos','C','E','I',['K','O'],b,'#bf1e24');
 breakdownTable_(s,9,17,'BONUS TURNOVER',['BTO Method','Turnover','EV Taken','Expected BTO %','Actual Return','Actual BTO %'],MB.BTO_METHODS,'BTO','C','E','I',['J','N'],b,'#9a7600');
}
function breakdownTable_(s,row,col,title,headers,items,source,typeCol,toCol,evCol,actualCols,b,color){
 s.getRange(row,col,1,headers.length).merge().setValue(title).setBackground(color).setFontColor('white').setFontWeight('bold');s.getRange(row+1,col,1,headers.length).setValues([headers]).setBackground(color).setFontColor('white').setFontWeight('bold');s.getRange(row+2,col,items.length,1).setValues(items.map(x=>[x]));
 const q=c=>`'${source}'!${c}:${c}`,sum=(c,key)=>`SUMIFS(${q(c)},${q(typeCol)},${key},${q('A')},">="&${b.start},${q('A')},"<="&${b.end})`;
 items.forEach((_,i)=>{const r=row+2+i,key=s.getRange(r,col).getA1Notation(),turn=s.getRange(r,col+1).getA1Notation(),ev=s.getRange(r,col+2).getA1Notation();s.getRange(r,col+1).setFormula('='+sum(toCol,key));s.getRange(r,col+2).setFormula('='+sum(evCol,key));const actual=actualCols.map(c=>sum(c,key)).join('+');if(source==='Promos'){s.getRange(r,col+3).setFormula('='+actual);s.getRange(r,col+4).setFormula(`=IF(${turn}=0,"",${ev}/${turn})`);s.getRange(r,col+5).setFormula(`=IF(${turn}=0,"",${s.getRange(r,col+3).getA1Notation()}/${turn})`);}else{s.getRange(r,col+3).setFormula(`=IF(${turn}=0,"",${ev}/${turn})`);s.getRange(r,col+4).setFormula('='+actual);s.getRange(r,col+5).setFormula(`=IF(${turn}=0,"",${s.getRange(r,col+4).getA1Notation()}/${turn})`);}if(headers.length===7)s.getRange(r,col+6).setFormula(`=IF(${turn}=0,"",${turn}/SUM(${s.getRange(row+2,col+1,items.length,1).getA1Notation()}))`);});
 const total=row+2+items.length;s.getRange(total,col).setValue('TOTAL').setFontWeight('bold');for(let c=1;c<headers.length;c++){const letter=mbColA1_(col+c);if([1,2,3,4].includes(c))s.getRange(total,col+c).setFormula(`=SUM(${letter}${row+2}:${letter}${total-1})`);}s.getRange(total,col,1,headers.length).setBackground(color==='#9a7600'?'#fff2cc':color==='#17652a'?'#d9ead3':'#f4cccc').setFontWeight('bold');
}
function buildMaster_(){
 const s=mbSheet_('Master PnL');mbEnsureSize_(s,90,18);s.getRange(1,1,s.getMaxRows(),18).clearContent();s.getRange('A1:R1').merge().setValue('MASTER PnL DASHBOARD').setBackground('#1f2933').setFontColor('white').setFontWeight('bold');
 masterSection_(s,3,1,'PROMOS BY EV TIER',['EV Tier','Turnover','Estimated EV','EV %','Actual PnL','POT %'],['A+','A','B','C','D','E'],'#17652a','tier');
 masterSection_(s,3,8,'PROMO PERFORMANCE BY TYPE',['Promo Type','Turnover','Estimated EV','EV %','Actual PnL','POT %','Percentage of Promo Turnover'],MB.PROMOS.map(x=>x[0]),'#17652a','promo');
 const blocks=[['BONUS TURNOVER',['Turnover','EV Taken','Expected BTO %','Actual Return','Actual BTO %'],['=SUM(BTO!E2:E)','=SUM(BTO!I2:I)','=IF(A15=0,"",B15/A15)','=SUM(BTO!J2:J)+SUM(BTO!N2:N)','=IF(A15=0,"",D15/A15)'],'#9a7600'],['NONPROMOS',['Turnover','Expected EV','EV %','Actual PnL','POT %'],['=SUM(NonPromos!E2:E)','=SUM(NonPromos!I2:I)','=IF(A19=0,"",B19/A19)','=SUM(NonPromos!K2:K)+SUM(NonPromos!O2:O)','=IF(A19=0,"",D19/A19)'],'#bf1e24']];
 blocks.forEach((b,i)=>{const r=13+i*4;s.getRange(r,1,1,5).merge().setValue(b[0]).setBackground(b[3]).setFontColor('white').setFontWeight('bold');s.getRange(r+1,1,1,5).setValues([b[1]]).setFontWeight('bold');b[2].forEach((f,j)=>s.getRange(r+2,j+1).setFormula(f));});
 const pnl=[['PROFIT/LOSS STATEMENT','EV','Actual'],['Promos','=SUM(Promos!H2:H)','=SUM(Promos!I2:I)+SUM(Promos!J2:J)'],['BTO','=SUM(BTO!I2:I)','=SUM(BTO!J2:J)+SUM(BTO!N2:N)'],['NonPromos','=SUM(NonPromos!I2:I)','=SUM(NonPromos!K2:K)+SUM(NonPromos!O2:O)'],['Overall EV','=SUM(B23:B25)',''],['Overall actual','', '=SUM(C23:C25)'],['Actual minus EV','', '=C27-B26']];s.getRange(22,1,pnl.length,3).setValues(pnl.map(r=>r.map(v=>String(v).startsWith('=')?'':v)));pnl.forEach((r,i)=>r.forEach((v,j)=>{if(String(v).startsWith('='))s.getRange(22+i,1+j).setFormula(v);}));s.getRange('A22:C22').setBackground('#00695c').setFontColor('white').setFontWeight('bold');
 const bank=[['ACCOUNTS AND BANKROLL','Value'],['Current Cash Balance','=SUM(Accounts!C5:C)'],['Current Bonus Balance','=SUM(Accounts!D5:D)'],['Current Bank Balance','0'],['Total Bankroll excluding bonuses','=B31+B33'],['Pending Withdrawals','=SUM(Accounts!F5:F)'],['Risk Exposure','=SUM(Accounts!I5:I)']];s.getRange(30,1,bank.length,2).setValues(bank.map(r=>[r[0],String(r[1]).startsWith('=')?'':r[1]]));bank.forEach((r,i)=>{if(String(r[1]).startsWith('='))s.getRange(30+i,2).setFormula(r[1]);});s.getRange('A30:B30').setBackground('#4c1d95').setFontColor('white').setFontWeight('bold');
 const actions=[['ACTION ITEMS','Count / Amount'],['Accounts generated','=COUNTA(Account_ID_List)'],['Banned accounts holding money','=COUNTIFS(Accounts!L5:L,"banned",Accounts!C5:C,">0")'],['StatDec accounts holding money','=COUNTIFS(Accounts!L5:L,"restricted/review",Accounts!C5:C,">0")'],['Pending withdrawals','=SUM(Accounts!F5:F)'],['Accounts with negative calculated balances','=COUNTIF(Accounts!C5:C,"<0")+COUNTIF(Accounts!D5:D,"<0")'],['Missing or invalid Account IDs','=COUNTIFS(Promos!A2:A,"<>",Promos!B2:B,"")+COUNTIFS(BTO!A2:A,"<>",BTO!B2:B,"")+COUNTIFS(NonPromos!A2:A,"<>",NonPromos!B2:B,"")']];s.getRange(39,1,actions.length,2).setValues(actions.map(r=>[r[0],String(r[1]).startsWith('=')?'':r[1]]));actions.forEach((r,i)=>{if(String(r[1]).startsWith('='))s.getRange(39+i,2).setFormula(r[1]);});s.getRange('A39:B39').setBackground('#3f3f3f').setFontColor('white').setFontWeight('bold');
}
function masterSection_(s,row,col,title,headers,items,color,kind){s.getRange(row,col,1,headers.length).merge().setValue(title).setBackground(color).setFontColor('white').setFontWeight('bold');s.getRange(row+1,col,1,headers.length).setValues([headers]).setBackground(color).setFontColor('white').setFontWeight('bold');s.getRange(row+2,col,items.length,1).setValues(items.map(x=>[x]));items.forEach((_,i)=>{const r=row+2+i,key=mbColA1_(col)+r;if(kind==='promo'){s.getRange(r,col+1).setFormula(`=SUMIF(Promos!C:C,${key},Promos!E:E)`);s.getRange(r,col+2).setFormula(`=SUMIF(Promos!C:C,${key},Promos!H:H)`);s.getRange(r,col+4).setFormula(`=SUMIF(Promos!C:C,${key},Promos!I:I)+SUMIF(Promos!C:C,${key},Promos!J:J)`);}else{const rate='IFNA(VLOOKUP(Promos!C2:C,Settings!A2:B,2,FALSE),-1)',tier=`ARRAYFORMULA(LOOKUP(${rate},SORT({Settings!E2:E7,Settings!D2:D7},1,TRUE),2))`;s.getRange(r,col+1).setFormula(`=IFNA(SUM(FILTER(Promos!E2:E,${tier}=${key})),0)`);s.getRange(r,col+2).setFormula(`=IFNA(SUM(FILTER(Promos!H2:H,${tier}=${key})),0)`);s.getRange(r,col+4).setFormula(`=IFNA(SUM(FILTER(Promos!I2:I+Promos!J2:J,${tier}=${key})),0)`);}const turn=s.getRange(r,col+1).getA1Notation();s.getRange(r,col+3).setFormula(`=IF(${turn}=0,"",${s.getRange(r,col+2).getA1Notation()}/${turn})`);s.getRange(r,col+5).setFormula(`=IF(${turn}=0,"",${s.getRange(r,col+4).getA1Notation()}/${turn})`);if(headers.length===7)s.getRange(r,col+6).setFormula(`=IF(${turn}=0,"",${turn}/SUM(Promos!E:E))`);});}
